[project]
name = "python-async-await"
version = "0.1.0"
description = "Examples for the blog post \"Understanding Async/Await in Python\""
authors = ["Zech Zimmerman <hi@zech.codes>"]
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.27.2",
    "requests>=2.32.3",
]
